# Copyright (C) 2017 The XPerience Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/santoni/setup-makefiles.sh

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/xiaomi/santoni/proprietary,system)

PRODUCT_PACKAGES += \
    libsdm-disp-apis \
    libtime_genoff \
    libts_detected_face_hal \
    libts_face_beautify_hal \
    QtiTelephonyService \
    TimeService \
    datastatusnotification \
    embms \
    fastdormancy \
    shutdownlistener \
    CNEService \
    QtiTetherService \
    com.qualcomm.location \
    qcrilmsgtunnel \
    ims \
    imssettings \
    com.qti.location.sdk \
    qcrilhook \
    qdcm_calib_data_hx8394F_HD720p_video_BOE \
    qdcm_calib_data_ili9881c_HD720p_video_Ebbg \
    qdcm_calib_data_ili9881c_HD720p_video_EbbgDJN
